package grupo11.planillaexcel.ventana;

import java.awt.Color;
import javax.swing.JPanel;

/**
 *
 * @author Joaquín León
 */
public class Planilla extends JPanel {
        public Planilla() {
                super();
                this.setBackground(new Color(184, 212, 191));
                this.initComponents();
        }
                /**
         * This method is called from within the constructor to initialize the
         * form. WARNING: Do NOT modify this code. The content of this method is
         * always regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
        private void initComponents() {

                jScrollPane1 = new javax.swing.JScrollPane();
                jTable1 = new javax.swing.JTable();

                jTable1.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
                jTable1.setModel(new javax.swing.table.DefaultTableModel(
                        new Object [][] {
                                { new Short((short) 1), null, null, null, null, null, null},
                                { new Short((short) 2), null, null, null, null, null, null},
                                { new Short((short) 3), null, null, null, null, null, null},
                                { new Short((short) 4), null, null, null, null, null, null},
                                { new Short((short) 5), null, null, null, null, null, null},
                                { new Short((short) 6), null, null, null, null, null, null},
                                { new Short((short) 7), null, null, null, null, null, null},
                                { new Short((short) 8), null, null, null, null, null, null},
                                { new Short((short) 9), null, null, null, null, null, null},
                                { new Short((short) 10), null, null, null, null, null, null},
                                { new Short((short) 11), null, null, null, null, null, null},
                                { new Short((short) 12), null, null, null, null, null, null},
                                { new Short((short) 13), null, null, null, null, null, null},
                                { new Short((short) 14), null, null, null, null, null, null},
                                { new Short((short) 15), null, null, null, null, null, null}
                        },
                        new String [] {
                                "", "A", "B", "C", "D", "E", "F"
                        }
                ) {
                        Class[] types = new Class [] {
                                java.lang.Short.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
                        };
                        boolean[] canEdit = new boolean [] {
                                false, true, true, true, true, true, true
                        };

                        public Class getColumnClass(int columnIndex) {
                                return types [columnIndex];
                        }

                        public boolean isCellEditable(int rowIndex, int columnIndex) {
                                return canEdit [columnIndex];
                        }
                });
                jTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
                jScrollPane1.setViewportView(jTable1);

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
                this.setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                                .addContainerGap())
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(22, Short.MAX_VALUE))
                );
        }// </editor-fold>                        


        // Variables declaration - do not modify                     
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JTable jTable1;
        // End of variables declaration        
}
