/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package grupo11.planillaexcel.ventana;

import javax.swing.BorderFactory;
import javax.swing.JViewport;

/**
 *
 * @author HOME
 */
public class Planilla extends javax.swing.JPanel {

        /**
         * Creates new form Planilla
         */
        public Planilla() {
                initComponents();
                this.Celdas.getModel().addTableModelListener(new Calculadora());
        }

        /**
         * This method is called from within the constructor to initialize the
         * form. WARNING: Do NOT modify this code. The content of this method is
         * always regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                Tabla = new javax.swing.JScrollPane();
                Celdas = new javax.swing.JTable();

                setAlignmentX(0.6F);
                setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
                setMaximumSize(new java.awt.Dimension(32770, 32767));
                setPreferredSize(new java.awt.Dimension(510, 291));

                Tabla.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
                Tabla.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
                Tabla.setToolTipText("");
                Tabla.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
                Tabla.setViewportBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
                Tabla.setAlignmentX(1.0F);
                Tabla.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
                Tabla.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
                Tabla.setName("Hello world"); // NOI18N
                Tabla.setOpaque(false);
                Tabla.setPreferredSize(new java.awt.Dimension(460, 404));

                Celdas.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
                Celdas.setModel(new javax.swing.table.DefaultTableModel(
                        new Object [][] {
                                { new Byte((byte) 1), null, null, null, null, null, null},
                                { new Byte((byte) 2), null, null, null, null, null, null},
                                { new Byte((byte) 3), null, null, null, null, null, null},
                                { new Byte((byte) 4), null, null, null, null, null, null},
                                { new Byte((byte) 5), null, null, null, null, null, null},
                                { new Byte((byte) 6), null, null, null, null, null, null},
                                { new Byte((byte) 7), null, null, null, null, null, null},
                                { new Byte((byte) 8), null, null, null, null, null, null},
                                { new Byte((byte) 9), null, null, null, null, null, null},
                                { new Byte((byte) 10), null, null, null, null, null, null},
                                { new Byte((byte) 11), null, null, null, null, null, null},
                                { new Byte((byte) 12), null, null, null, null, null, null},
                                { new Byte((byte) 13), null, null, null, null, null, null},
                                { new Byte((byte) 14), null, null, null, null, null, null},
                                { new Byte((byte) 15), null, null, null, null, null, null}
                        },
                        new String [] {
                                "", "A", "B", "C", "D", "E", "F"
                        }
                ) {
                        Class[] types = new Class [] {
                                java.lang.Byte.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
                        };
                        boolean[] canEdit = new boolean [] {
                                false, true, true, true, true, true, true
                        };

                        public Class getColumnClass(int columnIndex) {
                                return types [columnIndex];
                        }

                        public boolean isCellEditable(int rowIndex, int columnIndex) {
                                return canEdit [columnIndex];
                        }
                });
                Celdas.setToolTipText("Hello world");
                Celdas.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_NEXT_COLUMN);
                Celdas.setAutoscrolls(false);
                Celdas.setColumnSelectionAllowed(true);
                Celdas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
                Celdas.setEditingColumn(1);
                Celdas.setEditingRow(1);
                Celdas.setGridColor(new java.awt.Color(240, 240, 240));
                Celdas.setMinimumSize(new java.awt.Dimension(100, 240));
                Celdas.setSelectionBackground(new java.awt.Color(129, 128, 166));
                Celdas.getTableHeader().setResizingAllowed(false);
                Celdas.getTableHeader().setReorderingAllowed(false);
                Tabla.setViewportView(Celdas);

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
                this.setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(Tabla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(Tabla, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)
                                .addContainerGap())
                );
        }// </editor-fold>//GEN-END:initComponents


        // Variables declaration - do not modify//GEN-BEGIN:variables
        public javax.swing.JTable Celdas;
        private javax.swing.JScrollPane Tabla;
        // End of variables declaration//GEN-END:variables
}
